# Site settings
title: 
header-img: img/home-bg.png
email: corinnefox01@gmail.com
copyright_name: corinnefox01
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  corinnefox01
learn_profile: corinnefox01
email_username: corinnefox01@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
